<?php

declare(strict_types=1);

namespace SugiPHP\Profiling\Tests;

use SugiPHP\Profiling\Job;
use SugiPHP\Profiling\JobFinishListener;
use SugiPHP\Profiling\JobFinishListenerException;
use SugiPHP\Profiling\JobInterface;
use SugiPHP\Profiling\JobMeasurement;
use LogicException;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\TestCase;
use RuntimeException;

#[CoversClass(Job::class)]
#[UsesClass(JobMeasurement::class)]
#[UsesClass(JobFinishListenerException::class)]
class JobTest extends TestCase
{
    public function testImplementsJobInterface(): void
    {
        $job = new Job('render');

        $this->assertInstanceOf(JobInterface::class, $job);

        $job->finish();
    }

    public function testNameIsExposedAsPublicProperty(): void
    {
        $job = new Job('render');

        $this->assertSame('render', $job->name);

        $job->finish();
    }

    public function testIdIsAutoGeneratedAndUniqueWhenNotProvided(): void
    {
        $a = new Job('a');
        $b = new Job('b');

        $this->assertNotSame('', $a->id);
        $this->assertNotSame($a->id, $b->id);

        $a->finish();
        $b->finish();
    }

    public function testIdUsesProvidedValue(): void
    {
        $job = new Job('render', id: 'custom-id');

        $this->assertSame('custom-id', $job->id);

        $job->finish();
    }

    public function testIsFinishedIsFalseInitially(): void
    {
        $job = new Job('render');

        $this->assertFalse($job->isFinished());

        $job->finish();
    }

    public function testFinishMarksJobAsFinished(): void
    {
        $job = new Job('render');
        $job->finish();

        $this->assertTrue($job->isFinished());
    }

    public function testFinishReturnsMeasurementWithMatchingIdentity(): void
    {
        $job = new Job('render', id: 'job-1');
        $measurement = $job->finish();

        $this->assertInstanceOf(JobMeasurement::class, $measurement);
        $this->assertSame('job-1', $measurement->id);
        $this->assertSame('render', $measurement->name);
    }

    public function testFinishComputesPositiveDurationFromStartTime(): void
    {
        $job = new Job('render');
        usleep(1000);
        $measurement = $job->finish();

        $this->assertSame($job->startTime, $measurement->startTime);
        $this->assertGreaterThan(0, $measurement->duration);
    }

    public function testFinishMergesAdditionalContextWithConstructorContext(): void
    {
        $job = new Job('render', ['a' => 1]);
        $measurement = $job->finish(['b' => 2]);

        $this->assertSame(['a' => 1, 'b' => 2], $measurement->context);
    }

    public function testFinishContextOverridesConstructorContextOnKeyCollision(): void
    {
        $job = new Job('render', ['a' => 1]);
        $measurement = $job->finish(['a' => 2]);

        $this->assertSame(['a' => 2], $measurement->context);
    }

    public function testFinishThrowsWhenCalledTwice(): void
    {
        $job = new Job('render');
        $job->finish();

        $this->expectException(LogicException::class);
        $job->finish();
    }

    public function testFinishNotifiesListenerWithTheMeasurement(): void
    {
        $listener = new class implements JobFinishListener {
            public ?JobMeasurement $received = null;

            public function onJobFinish(JobMeasurement $measurement): void
            {
                $this->received = $measurement;
            }
        };

        $job = new Job('render', listener: $listener);
        $measurement = $job->finish();

        $this->assertSame($measurement, $listener->received);
    }

    public function testFinishWrapsListenerExceptionAndPreservesMeasurement(): void
    {
        $listener = new class implements JobFinishListener {
            public function onJobFinish(JobMeasurement $measurement): void
            {
                throw new RuntimeException('disk full');
            }
        };

        $job = new Job('render', id: 'job-1', listener: $listener);

        try {
            $job->finish();
            $this->fail('Expected JobFinishListenerException was not thrown.');
        } catch (JobFinishListenerException $e) {
            $this->assertSame('job-1', $e->getMeasurement()->id);
            $this->assertSame('render', $e->getMeasurement()->name);
            $this->assertInstanceOf(RuntimeException::class, $e->getPrevious());
            $this->assertSame('disk full', $e->getPrevious()->getMessage());
        }
    }

    public function testFinishMarksJobAsFinishedEvenWhenListenerThrows(): void
    {
        $listener = new class implements JobFinishListener {
            public function onJobFinish(JobMeasurement $measurement): void
            {
                throw new RuntimeException('disk full');
            }
        };

        $job = new Job('render', listener: $listener);

        try {
            $job->finish();
        } catch (JobFinishListenerException) {
            // expected
        }

        $this->assertTrue($job->isFinished());
    }

    public function testDestructWarnsWhenJobWasNeverFinished(): void
    {
        $captured = [];
        set_error_handler(function (int $errno, string $errstr) use (&$captured): bool {
            $captured[] = [$errno, $errstr];
            return true;
        });

        $job = new Job('leaked', id: 'leaked-id');
        unset($job);

        restore_error_handler();

        $this->assertCount(1, $captured);
        $this->assertSame(E_USER_WARNING, $captured[0][0]);
        $this->assertStringContainsString('leaked', $captured[0][1]);
        $this->assertStringContainsString('leaked-id', $captured[0][1]);
    }

    public function testDestructDoesNotWarnWhenJobWasFinished(): void
    {
        $captured = [];
        set_error_handler(function (int $errno, string $errstr) use (&$captured): bool {
            $captured[] = [$errno, $errstr];
            return true;
        });

        $job = new Job('render');
        $job->finish();
        unset($job);

        restore_error_handler();

        $this->assertCount(0, $captured);
    }
}
